### ISSUE TITLE
absence of delineation nifti files for cases with more than 1 lesion

### ISSUE THREAD

**Issue by ndebs** [DIAGNijmegen/picai_labels#1]
Dear organizers, 

Thanks a lot for these data and for organizing this great challenge ! I was wondering if it is normal that the nifti delineations for patients who have more than one lesion are missing on the repo? (e.g. 1000008, 10000029, 100036, etc)

Best regards,

Noëlie

**Comment by joeranbosma** [comment]
Hi Noëlle,

The annotations for those cases are indeed missing. In fact, there are many cases with csPCa, without lesion delineations. Out of the 1500 cases shared in the Public Training and Development Dataset, 1075 cases have benign tissue or indolent PCa (i.e., their labels should be empty or full of 0s) and 425 cases have csPCa (i.e., their labels should have lesion blobs of value 2, 3, 4 or 5). Out of these 425 positive cases, only 220 cases carry an annotation derived by a human expert. The remaining 205 positive cases have not been annotated (e.g., study 10008_100008, as encountered by you).

This is intentional, because it is infeasible to annotate all lesions at the scale of the private training dataset. Hence, we encourage participants to develop methods that can account for or figure out how to use non-annotated cases in the public training dataset as well.
 
At Radboudumc, we deal with such cases with a semi-supervised learning strategy (https://arxiv.org/abs/2112.05151). We will release AI-derived annotations for all 1500 training cases in 1-2 weeks, and all cases in the private training dataset (later in the challenge), using this method. You can choose to use these AI-derived annotations for non-annotated cases or another methodology for the same. For more information on this, please check out the [README.md of the picai_labels repo](https://github.com/DIAGNijmegen/picai_labels#dataset-characteristics) and the [study protocol detailed in our BIAS form](https://zenodo.org/record/6522364#.YqCleXZBwQ8).

It could be that cases with multiple lesions are more likely to lack a human expert delineation, I would need to check that. It is, however, not generally true that these annotations are missing. For example, 10268_1000272 has a 4+3 and 3+4 lesion annotated.

Hope this helps.
Joeran

**Comment by ndebs** [comment]
Ok, thanks a lot for your answer !
Best regards
Noëlie
