### ISSUE TITLE
ISUP 1 lesions

### ISSUE THREAD

**Issue by edupooch** [DIAGNijmegen/picai_labels#10]
Dear organizers,

I have been exploring the dataset for my research work, and I noticed there are 311 ISUP 1 lesions reported, but the expert-derived annotations for those weren't included in the dataset release. Were these samples not annotated or was the omission intentional to focus on the task of csPCa detection? Would it be possible to release the annotations for these samples as well?

Thank you for your hard work and dedication in putting together this dataset.

**Comment by joeranbosma** [comment]
Dear Eduardo,

Thanks for reaching out to us. The ISUP 1 lesions were only partially annotated, with many lesion masks missing (so while we did record their occurrence in the marksheet, we did not make voxel-wise lesion masks). This choice was made because they do not serve the primary objective of the PI-CAI challenge, but do take a lot of time to delineate.

I'm afraid the collection of these lesion masks would incur a lot of additional effort, which we rather spend differently.

All the best,
Joeran

**Comment by anindox8** [comment]
Indeed. To add upon @joeranbosma's remarks, some of these ISUP 1 lesions were really small (~1mm) and some were sampled via random systematic biopsies. So we couldn't reliably trace these histopathology findings back to their respective MRI scans, and create annotations with adequate certainty.
