### ISSUE TITLE
PX-0025 vs PICAI 11087

### ISSUE THREAD

**Issue by ndebs** [DIAGNijmegen/picai_labels#11]
Hi,
I recently noticed that for patient PX-0025 (a patient that has two exams), the given matching PICAI patient (https://github.com/DIAGNijmegen/picai_labels/blob/main/additional_resources/ProstateX-mapping.json) was 11087 : 

    "ProstateX-0025_04-15-2012": "11087_1001109",
    "ProstateX-0025_10-28-2011": "11087_1001110",

But when I checked the csv file with all information about PICAI dataset (https://github.com/DIAGNijmegen/picai_labels/blob/main/clinical_information/marksheet.csv), I found the following information about patient 11087 :   

11087 | 1001109 | 2012-05-10  ...
11087 | 1001110 | 2012-10-05  ...

It seems first that MRI dates from PICAI doesn't match ProstateX MRI dates, but also that the order of exams are reversed (meaning that in first table, study 1001109 appears to be the second exams while in second table it appears to be the first exams). 

Is this a mistake only for this patient? or could there be a date problem on other PICAI patients?

Thanks you !

Noëlie

**Comment by joeranbosma** [comment]
Hi Noëlie,

Thanks for raising this issue! I have check the dates for this patient, and I can confirm that the PI-CAI dates are consistent with what we have internally (the shifted dates fall within the range we expect), and the chronological order of the studies in the PI-CAI data is unchanged due to the anonymization date shift.

We can't tell you about the ProstateX anonymization scheme and what date shift was applied then, as this is too long ago and before our time.

So, I would follow the PI-CAI dates, and ignore the ProstateX dates.

Best,
Joeran

**Comment by ndebs** [comment]
Hi Joeran, 
Ok, thanks for your answer !
